server:
  error:
    include-message: always
    include-stacktrace: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
    enabled: false

lombok:
  fieldDefaults:
    defaultPrivate: true

logging:
  level:
    org.rent.app.service: DEBUG
